name: ec2 deploy CI
on:
  push:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout application code
        uses: actions/checkout@v4

      - name: Set up SSH  
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: /
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            set -e
            cd ${{secrets.APP_DIR}}

            echo "Pulling latest changes from Git repository..."
            git pull origin main

            echo "Stopping and removing existing container..."
            docker-compose down

            echo "Building and starting new container..."
            docker-compose up -d --build

            echo "cleanup unused Docker resources..."
            docker system prune -f

            echo "Deployment completed successfully."
          EOF

